### ISSUE TITLE
Opt-in support for the `WebSocket` wrapper(s) to send messages as "Text"?

### ISSUE THREAD

**Issue by airbreather** [dotnet/Nerdbank.Streams#719]
Considering this spot:
https://github.com/dotnet/Nerdbank.Streams/blob/3ec3e25ba48f3d59fe8c1220563d8fe71a17b8d8/src/Nerdbank.Streams/PipeExtensions.cs#L339

It sends using `WebSocketMessageType.Binary`, but this wrapper is a pretty decent way to connect `System.Text.Json` and `System.IO.Pipelines` together over a web socket.  Reading works as you'd expect, and writing stuff should look like this:
```csharp
PipeWriter writer = someWebSocket.UsePipe().Output;

// sending an arbitrary object across the Web Socket:
await JsonSerializer.SerializeAsync(writer.AsStream(true), value, s_jsonSerializerOptions, cancellationToken);

// or if I've buffered the UTF-8 bytes already:
await writer.WriteAsync(bytes, cancellationToken);
```

But of course, JSON is "text", so if I try to send this message to a receiver who treats "text" differently than "binary", they might not like what they see.  My specific use case is to chat with a [ArchipelagoMW/Archipelago](https://github.com/ArchipelagoMW/Archipelago) server: it calls [JSONDecoder.decode](https://docs.python.org/3/library/json.html#json.JSONDecoder.decode), which barfs if it gets `bytes` instead of a `str`.

I wonder if it would make sense to have something like this?
```csharp
PipeWriter writer = someWebSocket.UsePipe(messageType: WebSocketMessageType.Text).Output;
```
`UsePipe` would probably validate that the `messageType` is either `Text` or `Binary`, and I don't know if it's totally worth it to have the writer loop do like UTF-8 validation or anything like that... but as this is the only thing stopping me from using the helpers from `Nerdbank.Streams` as-is (and it's a hard blocker for my use case), I figured I'd drop in this suggestion before moving on.

**Comment by AArnott** [comment]
Thanks for the well thought out suggestion. I looked into the actual character encoding that websocket expects when claiming text, and it is indeed UTF-8, which matches what System.Text.Json creates. 
I don't think I'd want to take `WebSocketMessageType` in the `UsePipe` method since that enum has a `Close` value that doesn't make sense, and it may be useful to explicitly document that when opting into text that UTF-8 is required.
So how about a `UsePipe(bool)` overload with an xml doc comment on the parameter indicating this?

Wanna send a PR?
